üêætrain_main
üêætrain_on_gpu 2024-09-09 16:09:45.839938
Training data set : ['data/sl_data_0.npz', 'data/sl_data_1.npz', 'data/sl_data_10.npz', 'data/sl_data_11.npz', 'data/sl_data_12.npz', 'data/sl_data_13.npz', 'data/sl_data_14.npz', 'data/sl_data_15.npz', 'data/sl_data_16.npz', 'data/sl_data_17.npz', 'data/sl_data_18.npz', 'data/sl_data_2.npz', 'data/sl_data_3.npz', 'data/sl_data_4.npz', 'data/sl_data_5.npz']
Testing data set  : ['data/sl_data_6.npz', 'data/sl_data_7.npz', 'data/sl_data_8.npz', 'data/sl_data_9.npz']
torch.cuda.current_device:  0
torch.cuda.device_count:  2
torch.cuda.get_device_name(0):  TITAN RTX
torch.cuda.get_device_capability(0):  (7, 5)
torch.cuda.get_arch_list():  ['sm_37', 'sm_50', 'sm_60', 'sm_70', 'sm_75', 'sm_80', 'sm_86']
GPU 0: TITAN RTX
  Memory Usage: 5.97 MB / 108.00 MB
Traceback (most recent call last):
  File "/data/student/u2424004/igo/TantamaGo/env/lib/python3.7/site-packages/torch/cuda/__init__.py", line 686, in utilization
    import pynvml  # type: ignore[import]
ModuleNotFoundError: No module named 'pynvml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 95, in <module>
    train_main() # pylint: disable=E1120
  File "/data/student/u2424004/igo/TantamaGo/env/lib/python3.7/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/data/student/u2424004/igo/TantamaGo/env/lib/python3.7/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/data/student/u2424004/igo/TantamaGo/env/lib/python3.7/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/student/u2424004/igo/TantamaGo/env/lib/python3.7/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "train.py", line 88, in train_main
    train_on_gpu(program_dir=program_dir,board_size=size,  batch_size=BATCH_SIZE, epochs=EPOCHS)
  File "/data/student/u2424004/igo/TantamaGo/nn/learn.py", line 224, in train_on_gpu
    log_gpu_usage()###########
  File "/data/student/u2424004/igo/TantamaGo/nn/learn.py", line 28, in log_gpu_usage
    print(f"  Utilization: {torch.cuda.utilization(i)}%")
  File "/data/student/u2424004/igo/TantamaGo/env/lib/python3.7/site-packages/torch/cuda/__init__.py", line 688, in utilization
    raise ModuleNotFoundError("pynvml module not found, please install pynvml")
ModuleNotFoundError: pynvml module not found, please install pynvml
