üêætrain_main
    EPOCHS: 1
    BATCH_SIZE: 256
    kifu_dir: None
    size: 19
    use_gpu: True
    rl: False
    window_size: 300000
    network_name: DualNet_256_24
    npz_dir: data
    ddp: False
    rl_num: -1
    rl_datetime: 
    input_opt: 
üêætrain_on_gpu 2025-01-10 03:12:58.843536
[20250110_031259] device
torch.cuda.current_device:  0
torch.cuda.device_count:  2
torch.cuda.get_device_name(0):  GeForce GTX TITAN X
torch.cuda.get_device_name(1):  GeForce GTX TITAN X
torch.cuda.get_device_capability(0):  (5, 2)
torch.cuda.get_device_capability(1):  (5, 2)
Traceback (most recent call last):
  File "train.py", line 124, in <module>
    train_main() # pylint: disable=E1120
  File "/usr/local/anaconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "train.py", line 117, in train_main
    train_on_gpu(program_dir=program_dir,board_size=size,  batch_size=BATCH_SIZE, epochs=EPOCHS, network_name=network_name, npz_dir=npz_dir)
  File "/data/student/u2424004/igo/TantamaGo/nn/learn.py", line 194, in train_on_gpu
    print("torch.cuda.get_arch_list(): ", torch.cuda.get_arch_list())
AttributeError: module 'torch.cuda' has no attribute 'get_arch_list'
