üêætrain_main
üêætrain_on_gpu 2024-09-10 13:27:06.538262
Training data set : ['data/sl_data_0.npz', 'data/sl_data_1.npz', 'data/sl_data_2.npz', 'data/sl_data_3.npz']
Testing data set  : ['data/sl_data_4.npz', 'data/sl_data_5.npz']
torch.cuda.current_device:  0
torch.cuda.device_count:  1
torch.cuda.get_device_name(0):  TITAN RTX
Traceback (most recent call last):
  File "train.py", line 96, in <module>
    train_main() # pylint: disable=E1120
  File "/data/student/u2424004/igo/TantamaGo/env/lib/python3.7/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/data/student/u2424004/igo/TantamaGo/env/lib/python3.7/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/data/student/u2424004/igo/TantamaGo/env/lib/python3.7/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/student/u2424004/igo/TantamaGo/env/lib/python3.7/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "train.py", line 89, in train_main
    train_on_gpu(program_dir=program_dir,board_size=size,  batch_size=BATCH_SIZE, epochs=EPOCHS)
  File "/data/student/u2424004/igo/TantamaGo/nn/learn.py", line 157, in train_on_gpu
    print("torch.cuda.get_device_name(1): ", torch.cuda.get_device_name(1))
  File "/data/student/u2424004/igo/TantamaGo/env/lib/python3.7/site-packages/torch/cuda/__init__.py", line 341, in get_device_name
    return get_device_properties(device).name
  File "/data/student/u2424004/igo/TantamaGo/env/lib/python3.7/site-packages/torch/cuda/__init__.py", line 374, in get_device_properties
    raise AssertionError("Invalid device id")
AssertionError: Invalid device id
